### ISSUE TITLE
Provide option to track min/max/average resource utilization stats instead of recording periodic stats

### ISSUE THREAD

**Issue by elainethale** [NREL/jade#42]
Using jade v0.4.9, stats are not available after my run completes, e.g.:

![image](https://user-images.githubusercontent.com/4871688/129100233-a68171b1-110f-4799-9df4-602d79ba57bb.png)

I'm trying to run  `jade stats collect`, but that is taking many minutes to run and hasn't yet completed. I also felt compelled to get a debug node to run it on. What am I missing?

**Comment by daniel-thom** [comment]
I would guess that you did not enable collection of resource stats. That is disabled by default. You have to append `-r X` (where X is the monitor interval in seconds) to `jade submit-jobs`.

I could detect this condition in `jade stats show` and provide a meaningful message instead of dumping an empty table.

The command `jade stats collect` is a standalone source-monitoring tool. I intended it for uses case like
- You want to collect stats on your laptop while something else is running.
- You are running some application in an interactive session and want to monitor the stats.

The default behavior is to monitor indefinitely, which is why it never completed. My thought was that the user would press Ctrl-c when their app is done. Checkout the help for the command and feel free to comment on whether it should be more clear.

**Comment by elainethale** [comment]
Collecting resource stats was the default behavior in earlier versions of jade, yes? In general that would be my preference. The default collection rate could be set to be fairly slow, e.g., 60s, perhaps adjusted some based on walltime.

Alternatively, is it possible to specify this setting in the config file?

Of course I will start specifying -r X when I submit-jobs in the meantime ...

**Comment by daniel-thom** [comment]
I changed the behavior in v0.2.5 because most people using Jade weren't looking at the stats and the log files were getting very large. I'm open to polling users and adjusting it again. Another thing I could do is only collect memory and CPU stats by default. Network is usually a don't-care and disk stats don't measure Lustre I/Os.

In the meantime consider using the submitter-params config file. Refer to `jade config submitter-params --help`.

**Comment by daniel-thom** [comment]
Do you actually care about periodic stats? Another solution is to sample regularly (every second) but only record min/max/average on those samples at the end of a node allocation or on some much longer interval. This could give you the max memory usage every hour, every day, or per-node. There would be minimal storage consumption and this could be the default.

**Comment by elainethale** [comment]
I do not care about periodic stats and definitely up-vote that idea :)

**Comment by daniel-thom** [comment]
Ok, then the plan is to make this the default behavior:
- Take samples every second
- Track the min, max, and sum of each stat in memory.
- Record the min, max, and average when the node allocation completes.
- If the user provides `-r X` on the command line, follow the current behavior.
